### ISSUE TITLE
Import of podcast episode with no image fails

### ISSUE THREAD

**Issue by kookster** [PRX/cms.prx.org#268]
Tries to announce the image, even when it is nil:
```
ActionController::UrlGenerationError: No route matches {:action=>"options", :api_version=>"v1", :controller=>"api/base"} missing required keys: [:any]
/usr/local/bundle/gems/actionpack-4.2.7.1/lib/action_dispatch/journey/formatter.rb:46:in `generate'
/usr/local/bundle/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/route_set.rb:721:in `generate'
/usr/local/bundle/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/route_set.rb:752:in `generate'
/usr/local/bundle/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/route_set.rb:799:in `url_for'
/usr/local/bundle/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/route_set.rb:280:in `call'
/usr/local/bundle/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/route_set.rb:345:in `block (2 levels) in define_url_helper'
/usr/local/bundle/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/polymorphic_routes.rb:220:in `polymorphic_method'
/usr/local/bundle/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/polymorphic_routes.rb:134:in `polymorphic_path'
/usr/local/bundle/gems/hal_api-rails-0.2.9/lib/hal_api/representer/uri_methods.rb:46:in `self_url'
/app/app/representers/api/msg/image_representer.rb:10:in `self_url'
/usr/local/bundle/gems/hal_api-rails-0.2.9/lib/hal_api/representer/uri_methods.rb:18:in `block in self_link'
/usr/local/bundle/gems/roar-1.0.4/lib/roar/hypermedia.rb:80:in `instance_exec'
/usr/local/bundle/gems/roar-1.0.4/lib/roar/hypermedia.rb:80:in `run_link_block'
/usr/local/bundle/gems/roar-1.0.4/lib/roar/hypermedia.rb:68:in `block in compile_links_for'
/usr/local/bundle/gems/roar-1.0.4/lib/roar/hypermedia.rb:66:in `collect'
/usr/local/bundle/gems/roar-1.0.4/lib/roar/hypermedia.rb:66:in `compile_links_for'
/usr/local/bundle/gems/roar-1.0.4/lib/roar/hypermedia.rb:62:in `prepare_links!'
/usr/local/bundle/gems/roar-1.0.4/lib/roar/hypermedia.rb:139:in `block in create_links_definition!'
/usr/local/bundle/gems/uber-0.0.15/lib/uber/options.rb:96:in `instance_exec'
/usr/local/bundle/gems/uber-0.0.15/lib/uber/options.rb:96:in `proc!'
/usr/local/bundle/gems/uber-0.0.15/lib/uber/options.rb:82:in `evaluate_for'
/usr/local/bundle/gems/uber-0.0.15/lib/uber/options.rb:60:in `call'
/usr/local/bundle/gems/representable-2.3.0/lib/representable/binding.rb:130:in `evaluate_option'
/usr/local/bundle/gems/representable-2.3.0/lib/representable/binding.rb:100:in `get'
/usr/local/bundle/gems/representable-2.3.0/lib/representable/binding.rb:59:in `block in compile_fragment'
/usr/local/bundle/gems/representable-2.3.0/lib/representable/binding.rb:123:in `evaluate_option'
/usr/local/bundle/gems/representable-2.3.0/lib/representable/binding.rb:58:in `compile_fragment'
/usr/local/bundle/gems/representable-2.3.0/lib/representable/mapper.rb:73:in `compile_fragment'
/usr/local/bundle/gems/representable-2.3.0/lib/representable/mapper.rb:33:in `serialize_property'
/usr/local/bundle/gems/representable-2.3.0/lib/representable/mapper.rb:25:in `block in serialize'
/usr/local/bundle/gems/representable-2.3.0/lib/representable/mapper.rb:24:in `each'
/usr/local/bundle/gems/representable-2.3.0/lib/representable/mapper.rb:24:in `serialize'
/usr/local/bundle/gems/representable-2.3.0/lib/representable.rb:48:in `create_representation_with'
/usr/local/bundle/gems/representable-2.3.0/lib/representable/hash.rb:32:in `to_hash'
/usr/local/bundle/gems/roar-1.0.4/lib/roar/json/hal.rb:56:in `to_hash'
/usr/local/bundle/gems/representable-2.3.0/lib/representable/json.rb:40:in `to_json'
/usr/local/bundle/gems/hal_api-rails-0.2.9/lib/hal_api/representer/caches.rb:13:in `to_json'
/app/app/models/podcast_import.rb:278:in `announce_image'
/app/app/models/podcast_import.rb:223:in `create_story'
/app/app/models/podcast_import.rb:192:in `block in create_stories'
/app/app/models/podcast_import.rb:191:in `map'
/app/app/models/podcast_import.rb:191:in `create_stories'
/app/app/models/podcast_import.rb:46:in `import'
```

**Comment by kookster** [comment]
fixed
