### ISSUE TITLE
convert `pieces` table to utf8 from latin1

### ISSUE THREAD

**Issue by kookster** [PRX/cms.prx.org#307]
This needs to be run on prx01 for prx.org, but noting it her as well (I honesty thought this table had already been converted).

`ALTER TABLE pieces CONVERT TO CHARACTER SET utf8`

...should do the trick, tried it on `mediajoint_staging` on prx02 and it worked, and also ran it on the RDS db we use for cms-staging on ECS.

out of an abundance of caution, I actually duped the table to do this on prx02:
```
create table `pieces_utf` like `pieces`;
insert pieces_utf SELECT * FROM pieces;
ALTER TABLE pieces_utf CONVERT TO CHARACTER SET utf8;
rename table pieces to pieces_latin, pieces_utf to pieces;
```

**Comment by kookster** [comment]
original error
```
ActiveRecord::StatementInvalid: Mysql2::Error: Incorrect string value: '\xC5\x8D Per...' for column 'title' at row 1: INSERT INTO `pieces` (`app_version`, `creator_id`, `account_id`, `title`, `short_description`, `description`, `published_at`, `series_id`, `deleted_at`, `status`, `status_message`, `created_at`, `updated_at`) VALUES ('v4', 8, 8, '\"Music for Wood and Strings\" | Sō Percussion', '\"Music for Wood and Strings\" | Sō Percussion', 'Sō Percussion creates adventurous compositions with new, unconventional instruments. Performing \"Music for Wood and Strings\" by Bryce Dessner of The National, the quartet plays custom-made dulcimer-like instruments that combine the sound of an electric guitar with the percussionist\'s toolkit to create a hypnotic effect.', '2017-03-31 12:34:06', 36721, '2017-04-07 21:18:22', 'invalid', 'Story \'\"Music for Wood and Strings\" | Sō Percussion\' has no audio.', '2017-04-07 21:18:22', '2017-04-07 21:18:22')
	from /usr/local/bundle/gems/mysql2-0.4.5/lib/mysql2/client.rb:120:in `_query'
	from /usr/local/bundle/gems/mysql2-0.4.5/lib/mysql2/client.rb:120:in `block in query'
	from /usr/local/bundle/gems/mysql2-0.4.5/lib/mysql2/client.rb:119:in `handle_interrupt'
	from /usr/local/bundle/gems/mysql2-0.4.5/lib/mysql2/client.rb:119:in `query'
	from /usr/local/bundle/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:309:in `block in execute'
	from /usr/local/bundle/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
	from /usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
	from /usr/local/bundle/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
	from /usr/local/bundle/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:309:in `execute'
	from /usr/local/bundle/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/mysql2_adapter.rb:231:in `execute'
	from /usr/local/bundle/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/mysql2_adapter.rb:248:in `exec_insert'
	from /usr/local/bundle/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:108:in `insert'
	from /usr/local/bundle/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/query_cache.rb:14:in `insert'
	from /usr/local/bundle/gems/activerecord-4.2.7.1/lib/active_record/relation.rb:64:in `insert'
	from /usr/local/bundle/gems/activerecord-4.2.7.1/lib/active_record/persistence.rb:524:in `_create_record'
	from /usr/local/bundle/gems/activerecord-4.2.7.1/lib/active_record/counter_cache.rb:139:in `_create_record'
... 56 levels...
	from /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/commands/console.rb:9:in `start'
	from /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/commands.rb:17:in `<top (required)>'
	from /usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
	from /usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
	from /usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
	from /app/bin/rails:9:in `<top (required)>'
	from /usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
	from /usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `block in load'
	from /usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
	from /usr/local/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'
```

**Comment by kookster** [comment]
this is deployed to production now
