### ISSUE TITLE
Podcast Imports: deadlock on `audio_file_templates` table.

### ISSUE THREAD

**Issue by svevang** [PRX/cms.prx.org#460]
There are deadlocks when posting to the audio_file_template controller:
Let's sidestep the transactions and move the update outside the locking transaction:

- [x] Move  invocations of `touch` to the `after_commit` hook

**Comment by svevang** [comment]
per mysql's `innodb_print_all_deadlocks`:

```
TRANSACTION 386663, ACTIVE 1 sec starting index read
mysql tables in use 1, locked 1
LOCK WAIT 12 lock struct(s), heap size 1136, 1376 row lock(s), undo log entries 2
MySQL thread id 349, OS thread handle 140667500607232, query id 1701481 172.19.0.2 root updating
UPDATE `series` SET `series`.`updated_at` = '2018-09-21 16:46:05' WHERE `series`.`id` = 37611
RECORD LOCKS space id 232 page no 708 n bits 80 index PRIMARY of table `shared_exchange_db`.`series` trx id 386663 lock_mode X locks rec but not gap waiting
Record lock, heap no 10 PHYSICAL RECORD: n_fields 25; compact format; info bits 0
 0: len 4; hex 800092eb; asc     ;;
 1: len 6; hex 00000005e65f; asc      _;;
 2: len 7; hex 01000000e0077a; asc       z;;
 3: len 4; hex 8003599b; asc   Y ;;
 4: len 30; hex 50524927732054686520576f726c643a204c61746573742045646974696f; asc PRI's The World: Latest Editio; (total 31 bytes);
 5: len 5; hex 99a0eb0b83; asc      ;;
 6: len 5; hex 99a0eb0b85; asc      ;;
 7: len 30; hex 486f7374204d6172636f205765726d616e20616e6420686973207465616d; asc Host Marco Werman and his team; (total 251 bytes);
 8: len 30; hex 486f7374204d6172636f205765726d616e20616e6420686973207465616d; asc Host Marco Werman and his team; (total 251 bytes);
 9: SQL NULL;
 10: SQL NULL;
 11: SQL NULL;
 12: len 5; hex 99a0eb0b83; asc      ;;
 13: SQL NULL;
 14: SQL NULL;
 15: SQL NULL;
 16: SQL NULL;
 17: SQL NULL;
 18: SQL NULL;
 19: SQL NULL;
 20: SQL NULL;
 21: SQL NULL;
 22: SQL NULL;
 23: SQL NULL;
 24: len 2; hex 7634; asc v4;;

TRANSACTION 386661, ACTIVE 1 sec starting index read
mysql tables in use 1, locked 1
6328 lock struct(s), heap size 696528, 385543 row lock(s), undo log entries 1
MySQL thread id 384, OS thread handle 140667499734784, query id 1701482 172.19.0.3 root updating
UPDATE `audio_file_templates` SET `position` = (`audio_file_templates`.`position` + 1), `updated_at` = '2018-09-21 16:46:06.751814' WHERE `audio_file_templates`.`audio_version_template_id` = 1364 AND (`audio_file_templates`.`position` >= 1)
RECORD LOCKS space id 232 page no 708 n bits 80 index PRIMARY of table `shared_exchange_db`.`series` trx id 386661 lock_mode X locks rec but not gap
Record lock, heap no 10 PHYSICAL RECORD: n_fields 25; compact format; info bits 0
 0: len 4; hex 800092eb; asc     ;;
 1: len 6; hex 00000005e65f; asc      _;;
 2: len 7; hex 01000000e0077a; asc       z;;
 3: len 4; hex 8003599b; asc   Y ;;
 4: len 30; hex 50524927732054686520576f726c643a204c61746573742045646974696f; asc PRI's The World: Latest Editio; (total 31 bytes);
 5: len 5; hex 99a0eb0b83; asc      ;;
 6: len 5; hex 99a0eb0b85; asc      ;;
 7: len 30; hex 486f7374204d6172636f205765726d616e20616e6420686973207465616d; asc Host Marco Werman and his team; (total 251 bytes);
 8: len 30; hex 486f7374204d6172636f205765726d616e20616e6420686973207465616d; asc Host Marco Werman and his team; (total 251 bytes);
 9: SQL NULL;
 10: SQL NULL;
 11: SQL NULL;
 12: len 5; hex 99a0eb0b83; asc      ;;
 13: SQL NULL;
 14: SQL NULL;
 15: SQL NULL;
 16: SQL NULL;
 17: SQL NULL;
 18: SQL NULL;
 19: SQL NULL;
 20: SQL NULL;
 21: SQL NULL;
 22: SQL NULL;
 23: SQL NULL;
 24: len 2; hex 7634; asc v4;;

RECORD LOCKS space id 138 page no 5 n bits 352 index PRIMARY of table `shared_exchange_db`.`audio_file_templates` trx id 386661 lock_mode X waiting
Record lock, heap no 2 PHYSICAL RECORD: n_fields 10; compact format; info bits 0
 0: len 4; hex 80000001; asc     ;;
 1: len 6; hex 0000000018ad; asc       ;;
 2: len 7; hex 82000000d70110; asc        ;;
 3: len 4; hex 80000070; asc    p;;
 4: len 4; hex 80000001; asc     ;;
 5: len 0; hex ; asc ;;
 6: SQL NULL;
 7: SQL NULL;
 8: len 5; hex 9995a708c1; asc      ;;
 9: len 5; hex 9995a708c1; asc      ;;
```

**Comment by svevang** [comment]
Request Log:
```
cms_1            | I, [2018-10-01T00:21:42.157143 #16]  INFO -- : Started POST "/api/v1/audio_version_templates/1407/audio_file_templates" for 172.20.0.6 at 2018-10-01 00:21:42 +0000                                                                                     
cms_1            | I, [2018-10-01T00:21:42.368047 #16]  INFO -- : Processing by Api::AudioFileTemplatesController#create as HAL                                                                                                                                            
cms_1            | I, [2018-10-01T00:21:42.368105 #16]  INFO -- :   Parameters: {"api_version"=>"v1", "audio_version_template_id"=>"1407"}                                                                                                                                 
cms_1            | W, [2018-10-01T00:21:42.368231 #16]  WARN -- : Can't verify CSRF token authenticity                                                                                                                                                                     
cms_1            | D, [2018-10-01T00:21:42.368992 #16] DEBUG -- : Unpermitted parameter: audio_version_template_id                                                                                                                                                         
cms_1            | D, [2018-10-01T00:21:42.370388 #16] DEBUG -- :   AudioVersionTemplate Load (0.4ms)  SELECT  `audio_version_templates`.* FROM `audio_version_templates` WHERE `audio_version_templates`.`id` = 1407 LIMIT 1                                              
cms_1            | D, [2018-10-01T00:21:42.371821 #16] DEBUG -- :   Series Load (0.3ms)  SELECT  `series`.* FROM `series` WHERE (`series`.`deleted_at` IS NULL OR `series`.`app_version` = 'v4') AND `series`.`id` = 37634 LIMIT 1                                         
cms_1            | D, [2018-10-01T00:21:42.372894 #16] DEBUG -- :   Account Load (0.3ms)  SELECT  `accounts`.* FROM `accounts` WHERE `accounts`.`id` = 219547 LIMIT 1                                                                                                      
cms_1            | D, [2018-10-01T00:21:42.373377 #16] DEBUG -- :    (0.2ms)  BEGIN                                                                                                                                                                                        
cms_1            | D, [2018-10-01T00:21:42.375395 #16] DEBUG -- :   SQL (1.0ms)  UPDATE `audio_file_templates` SET `position` = (`audio_file_templates`.`position` + 1), `updated_at` = '2018-10-01 00:21:42.374211' WHERE `audio_file_templates`.`audio_version_template_id
` = 1407 AND (`audio_file_templates`.`position` >= 1)                                                                                                                                                                                                                      
cms_1            | D, [2018-10-01T00:21:42.376173 #16] DEBUG -- :   SQL (0.4ms)  INSERT INTO `audio_file_templates` (`audio_version_template_id`, `position`, `label`, `length_minimum`, `length_maximum`, `created_at`, `updated_at`) VALUES (1407, 1, 'Main Segment', 0, 0
, '2018-10-01 00:21:42', '2018-10-01 00:21:42')                                                                                                                                                                                                                            
cms_1            | D, [2018-10-01T00:21:42.377214 #16] DEBUG -- :   SQL (0.3ms)  UPDATE `audio_version_templates` SET `audio_version_templates`.`updated_at` = '2018-10-01 00:21:42' WHERE `audio_version_templates`.`id` = 1407                                           
cms_1            | D, [2018-10-01T00:21:43.656164 #16] DEBUG -- :   SQL (1277.8ms)  UPDATE `series` SET `series`.`updated_at` = '2018-10-01 00:21:42' WHERE `series`.`id` = 37634                                                                                          
cms_1            | D, [2018-10-01T00:21:43.657250 #16] DEBUG -- :    (0.3ms)  ROLLBACK                                                                                                                                                                                     
cms_1            | F, [2018-10-01T00:21:43.658379 #16] FATAL -- :                                                                                                                                                                                                          
cms_1            | Mysql2::Error (Deadlock found when trying to get lock; try restarting transaction):                                                                                                                                                                     
cms_1            |   app/controllers/concerns/resource_callbacks.rb:12:in `block in create'                                                                                                                                                                                
cms_1            |   app/controllers/concerns/resource_callbacks.rb:9:in `tap'                                                                                                                                                                                             
cms_1            |   app/controllers/concerns/resource_callbacks.rb:9:in `create'                                                                                                                                                                                          
cms_1            |   app/controllers/concerns/child_resource.rb:47:in `create'      
```

When series are created on the Publish side of things, the following happens on one side of the deadlock:

1) An `AudioFileTemplate` is posted to the API
2) `AudioFileTemplate` belongs_to and touches `AudioVersionTemplate`
3) `AudioVersionTemplate` belongs_to and touches `Series`

**Comment by svevang** [comment]
Another from `SHOW ENGINE INNODB STATUS;`:

```
------------------------                                                                                                                                                                                                                                                    
LATEST DETECTED DEADLOCK                                                                                                                                                                                                                                                    
------------------------                                                                                                                                                                                                                                                    
2018-10-01 00:21:43 0x7fb9542cc700                                                                                                                                                                                                                                          
*** (1) TRANSACTION:                                                                                                                                                                                                                                                        
TRANSACTION 1274690, ACTIVE 1 sec starting index read                                                                                                                                                                                                                       
mysql tables in use 1, locked 1                                                                                                                                                                                                                                             
LOCK WAIT 13 lock struct(s), heap size 1136, 1419 row lock(s), undo log entries 2                                                                                                                                                                                           
MySQL thread id 13, OS thread handle 140434629748480, query id 247194 172.19.0.2 root updating                                                                                                                                                                              
UPDATE `series` SET `series`.`updated_at` = '2018-10-01 00:21:42' WHERE `series`.`id` = 37634                                                                                                                                                                               
*** (1) WAITING FOR THIS LOCK TO BE GRANTED:                                                                                                                                                                                                                                
RECORD LOCKS space id 232 page no 709 n bits 72 index PRIMARY of table `shared_exchange_db`.`series` trx id 1274690 lock_mode X locks rec but not gap waiting                                                                                                               
Record lock, heap no 6 PHYSICAL RECORD: n_fields 25; compact format; info bits 0                                                                                                                                                                                            
 0: len 4; hex 80009302; asc     ;;                                                                                                                                                                                                                                         
 1: len 6; hex 000000137338; asc     s8;;                                                                                                                                                                                                                                   
 2: len 7; hex 020000019606a0; asc        ;;                                                                                                                                                                                                                                
 3: len 4; hex 8003599b; asc   Y ;;                                                                                                                                                                                                                                         
 4: len 28; hex 4f6e204265696e672077697468204b72697374612054697070657474; asc On Being with Krista Tippett;;                                                                                                                                                                
 5: len 5; hex 99a1020567; asc     g;;                                                                                                                                                                                                                                      
 6: len 5; hex 99a1020569; asc     i;;                                                                                                                                                                                                                                      
 7: len 30; hex 4f6e204265696e672074616b657320757020746865206269672071756573; asc On Being takes up the big ques; (total 233 bytes);                                                                                                                                        
 8: len 30; hex 47726f756e64627265616b696e6720506561626f64792041776172642d77; asc Groundbreaking Peabody Award-w; (total 250 bytes);                                                                                                                                        
 9: SQL NULL;                                                                                                                                                                                                                                                               
 10: SQL NULL;                                                                                                                                                                                                                                                              
 11: SQL NULL;                                                                                                                                                                                                                                                              
 12: len 5; hex 99a1020567; asc     g;;                                                                                                                                                                                                                                     
 13: SQL NULL;                                                                                                                                                                                                                                                              
 14: SQL NULL;                                                                                                                                                                                                                                                              
 15: SQL NULL;                                                                                                                                                                                                                                                              
 16: SQL NULL;                                                                                                                                                                                                                                                              
 17: SQL NULL;
 18: SQL NULL;
 19: SQL NULL;
 20: SQL NULL;
 21: SQL NULL;
 22: SQL NULL;
 23: SQL NULL;
 24: len 2; hex 7634; asc v4;;

*** (2) TRANSACTION:
TRANSACTION 1274689, ACTIVE 2 sec starting index read
mysql tables in use 1, locked 1
6354 lock struct(s), heap size 696528, 391603 row lock(s), undo log entries 1
MySQL thread id 31, OS thread handle 140433957897984, query id 247196 172.19.0.5 root updating
UPDATE `audio_file_templates` SET `position` = (`audio_file_templates`.`position` + 1), `updated_at` = '2018-10-01 00:21:43.588028' WHERE `audio_file_templates`.`audio_version_template_id` = 1408 AND (`audio_file_templates`.`position` >= 1)
*** (2) HOLDS THE LOCK(S):
RECORD LOCKS space id 232 page no 709 n bits 72 index PRIMARY of table `shared_exchange_db`.`series` trx id 1274689 lock_mode X locks rec but not gap
Record lock, heap no 6 PHYSICAL RECORD: n_fields 25; compact format; info bits 0
 0: len 4; hex 80009302; asc     ;;
 1: len 6; hex 000000137338; asc     s8;;
 2: len 7; hex 020000019606a0; asc        ;;
 3: len 4; hex 8003599b; asc   Y ;;
 4: len 28; hex 4f6e204265696e672077697468204b72697374612054697070657474; asc On Being with Krista Tippett;;
 5: len 5; hex 99a1020567; asc     g;;
 6: len 5; hex 99a1020569; asc     i;;
 7: len 30; hex 4f6e204265696e672074616b657320757020746865206269672071756573; asc On Being takes up the big ques; (total 233 bytes);
 8: len 30; hex 47726f756e64627265616b696e6720506561626f64792041776172642d77; asc Groundbreaking Peabody Award-w; (total 250 bytes);
 9: SQL NULL;
 10: SQL NULL;
 11: SQL NULL;
 12: len 5; hex 99a1020567; asc     g;;
 13: SQL NULL;
 14: SQL NULL;
 15: SQL NULL;
 16: SQL NULL;
 17: SQL NULL;
 18: SQL NULL;
 19: SQL NULL;
 20: SQL NULL;
 21: SQL NULL;
 22: SQL NULL;
 23: SQL NULL;
 24: len 2; hex 7634; asc v4;;

*** (2) WAITING FOR THIS LOCK TO BE GRANTED:
RECORD LOCKS space id 138 page no 5 n bits 352 index PRIMARY of table `shared_exchange_db`.`audio_file_templates` trx id 1274689 lock_mode X waiting
Record lock, heap no 2 PHYSICAL RECORD: n_fields 10; compact format; info bits 0
 0: len 4; hex 80000001; asc     ;;
 1: len 6; hex 0000000018ad; asc       ;;
 2: len 7; hex 82000000d70110; asc        ;;
 3: len 4; hex 80000070; asc    p;;
 4: len 4; hex 80000001; asc     ;;
 5: len 0; hex ; asc ;;
 6: SQL NULL;
 7: SQL NULL;
 8: len 5; hex 9995a708c1; asc      ;;
 9: len 5; hex 9995a708c1; asc      ;;

*** WE ROLL BACK TRANSACTION (1)
```

**Comment by svevang** [comment]
With some new podcast import testing data, I'm seeing an associated problem that seems related to model locks. Exceptions of this form are mixed into the podcast import process:

https://gist.githubusercontent.com/svevang/9c4e9d933268b38a783493cccb87995d/raw/2511808043c1998e19dafc0190db6acd5d386993/episode%2520import.traceback
