### ISSUE TITLE
Make encoding consistent across cms DB tables

### ISSUE THREAD

**Issue by svevang** [PRX/cms.prx.org#493]
Noticing that the audio files table is encoded as `latin1`, I see that tables in the cms/exchange db are variously encoded: 

- 106 tables encoded as `latin1`
- 104 tables encoded as `utf8mb4`
- 163 tables encoded as `utf8`

As a basis for string handling, it would be nice if these were all the same encoding. 

- [x] convert columns (preserve nullable and defaults)
- [x] convert tables (as default encoding)
- [x] convert database  (as default encoding)

**Comment by svevang** [comment]
So working through an incremental migration of the encodings over here:
https://github.com/PRX/cms.prx.org/issues/509

If the `character_set_client`, `character_set_connection`, and `character_set_results` are not set to `utf8mb4`, then the new `utf8mb4` columns on series behave as mysql’s `utf8`, e.g. they only support 3 byte characters. (edited) 
So ☃ is fine (3 bytes), but you can’t insert 😀 which is 4 bytes.

Running `SET NAMES utf8mb4;` within the active connection sets all three of those `character_set_*` settings.

**Comment by svevang** [comment]
- [ ] Verify that exchange connection encoding/collation is set up to use utf8 multibyte
- [ ] Verify how exchange posts utf-8 multibyte date to a latin1 table (will it error or will it save multibyte characters in latin1)

**Comment by svevang** [comment]
Re: connection encoding. Seeing at least one relevant encoding entry in exchange's database.yml, producing this in current exchange prod:

```
>> ActiveRecord::Base.connection.execute("SHOW SESSION VARIABLES LIKE 'character\_set\_%';").each_hash { |h| pp h }
{"Variable_name"=>"character_set_client", "Value"=>"utf8"}
{"Variable_name"=>"character_set_connection", "Value"=>"utf8"}
{"Variable_name"=>"character_set_database", "Value"=>"latin1"}
{"Variable_name"=>"character_set_filesystem", "Value"=>"binary"}
{"Variable_name"=>"character_set_results", "Value"=>"utf8"}
{"Variable_name"=>"character_set_server", "Value"=>"latin1"}
{"Variable_name"=>"character_set_system", "Value"=>"utf8"}
{"Variable_name"=>"character_sets_dir", "Value"=>"/rdsdbbin/mysql-5.7.31.R4/share/charsets/"}
```

Writes to a latin1 table/column in exchange with utf8 data produces an exception:

```
Mysql::Error: Incorrect string value: '\xE1\x9A\xA0\xE1\x9B\x87...' for column 'bio' at row 1: UPDATE `users` SET `favorite_shows` = '', `bio` = 'ᚠᛇᚻ᛫ᛒᛦᚦ᛫ᚠᚱᚩᚠᚢᚱ᛫ᚠᛁᚱᚪ᛫ᚷᛖᚻᚹᛦᛚᚳᚢᛗ', `influences` = '', `updated_at` = '2020-11-30 15:12:12' WHERE `id` = 245245

/ruby/lib/ruby/gems/1.8/bundler/gems/rails-c2be41e8dba7/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:227:in `log_without_newrelic_instrumentation'
/ruby/lib/ruby/gems/1.8/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/instrumentation/active_record.rb:67:in `log'
/ruby/lib/ruby/gems/1.8/bundler/gems/rails-c2be41e8dba7/activerecord/lib/active_record/connection_adapters/mysql_adapter.rb:324:in `execute'
/ruby/lib/ruby/gems/1.8/bundler/gems/rails-c2be41e8dba7/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:265:in `update_sql'
/ruby/lib/ruby/gems/1.8/bundler/gems/rails-c2be41e8dba7/activerecord/lib/active_record/connection_adapters/mysql_adapter.rb:339:in `update_sql'
/ruby/lib/ruby/gems/1.8/bundler/gems/rails-c2be41e8dba7/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:49:in `update_without_query_dirty'
/ruby/lib/ruby/gems/1.8/bundler/gems/rails-c2be41e8dba7/activerecord/lib/active_record/connection_adapters/abstract/query_cache.rb:19:in `update'
/ruby/lib/ruby/gems/1.8/bundler/gems/rails-c2be41e8dba7/activerecord/lib/active_record/base.rb:2950:in `update_without_lock'
```

**Comment by svevang** [comment]
##### Multibyte Data in the Shared Exchange Database

It appears that UTF-8 database connection character encoding landed in 2008 with: https://github.com/PRX/exchange.prx.org/commit/e53549b38b83ff15de422a315af547a6e6a2a349. Maybe some backend interactions with Solr precipitating that? At that point, UTF-8 data written to a latin1 column should have thrown errors. At least that is the behavior with the current mysql Gem. There's no Gemfile/lock at that revision .

At that point any _existing_ multibyte data in the database should have started to appear as mojibake. It's possible to see how that works by reverting exchange's database connection character set from UTF-8 back to latin1 in the `config/database.yml`.  Posting multibyte character data to a latin1 column appears to be working at that point. E.g. posting a `☃️` in the user bio form is successful and results in a `☃️` in the user's profile.  However, when switching the database character encoding _back_ to utf-8, refreshing the page results in the snowman appearing as `â˜ƒï¸` (UTF-8 bytes, decoded from latin1 to UTF-8) .  So theoretically, any mojibake weirdness would have been visible since https://github.com/PRX/exchange.prx.org/commit/e53549b38b83ff15de422a315af547a6e6a2a349 to be discovered and cleaned up.

Assuming the data _was_ written `utf-8 connection -> latin1 table/column` (before 2008, or perhaps by some later combination of gems/configuration), then the bytes were truncated and the data is gone. However, I've not seen that behavior with the current mysql gem + configurationsetup. As stated before, we get an error when trying to do save UTF-8 data into a latin1 col/table.

##### Brief Character Set Codepoint Analysis

We can see code points change across a character encoding change.  Mysql has a handy `HEX(..)` and `UNHEX(...)` function to print out the encoded characters as hex strings. So in the case of the user bio:

```
-- Look at records where the hex code points shift.
select id, bio
FROM users where hex(bio) != hex(CONVERT(bio USING utf8));
```

There are records where the codes stray out of the latin1 subset of UTF-8 .  Confusingly the MySQL latin1 character encoding is actually windows-1252, which is basically latin1 plus the so-called smart quotes. The windows-1252 encoding uses the reserved range of codes in latin1 to encode e.g. 0x92 as the single quote `’`. As in the case of exchange user 134, the bio starts out as `I’m  ...`, Looking at the hex output we can see the latin1 reserved / windows-1252 hex codepoint 0x92 is transformed to 0xE28099 (which is unicode U+2019 'RIGHT SINGLE QUOTATION MARK'). 

So it appears that the underlying character set conversion is working. However, it leaves us in the uncomfortable position of being unable to differentiate between properly transformed codepoints from improperly transformed -- assuming some multi-byte data was inserted prior to 2008. Though, it is likely that any 'weird' looking text data would have been fixed up over time.
