### ISSUE TITLE
Episode Import generates exceptions in logger

### ISSUE THREAD

**Issue by svevang** [PRX/cms.prx.org#519]
Possibly related to how we override the logger in Shoryuken jobs. There are cases where the logger generates errors.  Sql events percolate through an active support call chain and blow up when they lack the correct methods.

**Comment by svevang** [comment]
From PodcastImport#67  (which resulted in about 17 such errors):


```
2019-05-10T18:17:59Z 140 TID-gs5avrnfk ActiveJob/EpisodeImportJob/production_cms_podcast_import/f23af1ca-3f62-4a67-801a-a56447ddc7fc ERROR: Could not log "sql.active_record" event. NoMethodError: undefined method `end=' for nil:NilClass ["/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/subscriber.rb:96:in `finish'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/log_subscriber.rb:83:in `finish'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/notifications/fanout.rb:102:in `finish'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/notifications/fanout.rb:46:in `block in finish'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/notifications/fanout.rb:46:in `each'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/notifications/fanout.rb:46:in `finish'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/notifications/instrumenter.rb:36:in `finish'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/notifications/instrumenter.rb:25:in `instrument'",
 "/usr/local/bundle/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'",
 "/usr/local/bundle/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:317:in `execute'",
 "/usr/local/bundle/gems/activerecord-4.2.10/lib/active_record/connection_adapters/mysql2_adapter.rb:217:in `execute'",
 "/usr/local/bundle/gems/activerecord-4.2.10/lib/active_record/connection_adapters/mysql2_adapter.rb:221:in `exec_query'",
 "/usr/local/bundle/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/database_statements.rb:356:in `select'",
 "/usr/local/bundle/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/database_statements.rb:32:in `select_all'",
 "/usr/local/bundle/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/query_cache.rb:70:in `select_all'",
 "/usr/local/bundle/gems/activerecord-4.2.10/lib/active_record/querying.rb:39:in `find_by_sql'",
 "/usr/local/bundle/gems/activerecord-4.2.10/lib/active_record/relation.rb:639:in `exec_queries'",
 "/usr/local/bundle/gems/activerecord-4.2.10/lib/active_record/association_relation.rb:32:in `exec_queries'",
 "/usr/local/bundle/gems/activerecord-4.2.10/lib/active_record/relation.rb:515:in `load'",
 "/usr/local/bundle/gems/activerecord-4.2.10/lib/active_record/relation.rb:243:in `to_a'",
 "/usr/local/bundle/gems/activerecord-4.2.10/lib/active_record/associations/collection_association.rb:445:in `get_records'",
 "/usr/local/bundle/gems/activerecord-4.2.10/lib/active_record/associations/collection_association.rb:460:in `find_target'",
 "/usr/local/bundle/gems/activerecord-4.2.10/lib/active_record/associations/collection_association.rb:403:in `load_target'",
 "/usr/local/bundle/gems/activerecord-4.2.10/lib/active_record/associations/collection_proxy.rb:45:in `load_target'",
 "/usr/local/bundle/gems/activerecord-4.2.10/lib/active_record/associations/collection_proxy.rb:945:in `to_ary'",
 "/usr/local/bundle/gems/activerecord-4.2.10/lib/active_record/relation/delegation.rb:132:in `+'",
 "/usr/local/bundle/gems/activerecord-4.2.10/lib/active_record/relation/delegation.rb:132:in `public_send'",
 "/usr/local/bundle/gems/activerecord-4.2.10/lib/active_record/relation/delegation.rb:132:in `method_missing'",
 "/usr/local/bundle/gems/activerecord-4.2.10/lib/active_record/relation/delegation.rb:99:in `method_missing'",
 "/app/app/models/story.rb:211:in `tags'",
 "/app/app/models/story_distributions/episode_distribution.rb:95:in `episode_attributes'",
 "/app/app/models/story_distributions/episode_distribution.rb:57:in `create_or_update_episode'",
 "/app/app/models/episode_import.rb:250:in `create_or_update_episode!'",
 "/app/app/models/episode_import.rb:66:in `import'",
 "/app/app/jobs/episode_import_job.rb:7:in `perform'",
 "/usr/local/bundle/gems/activejob-4.2.10/lib/active_job/execution.rb:32:in `block in perform_now'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:117:in `call'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:505:in `call'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:343:in `block (2 levels) in simple'",
 "/app/app/jobs/application_job.rb:12:in `block (2 levels) in <class:ApplicationJob>'",
 "/usr/local/bundle/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'",
 "/app/app/jobs/application_job.rb:11:in `block in <class:ApplicationJob>'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:441:in `instance_exec'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:441:in `block in make_lambda'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:342:in `block in simple'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:497:in `block in around'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:505:in `call'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:343:in `block (2 levels) in simple'",
 "/usr/local/bundle/gems/newrelic_rpm-5.2.0.345/lib/new_relic/agent/transaction.rb:110:in `wrap'",
 "/usr/local/bundle/gems/newrelic_rpm-5.2.0.345/lib/new_relic/agent/instrumentation/active_job.rb:63:in `run_in_transaction'",
 "/usr/local/bundle/gems/newrelic_rpm-5.2.0.345/lib/new_relic/agent/instrumentation/active_job.rb:52:in `perform'",
 "/usr/local/bundle/gems/newrelic_rpm-5.2.0.345/lib/new_relic/agent/instrumentation/active_job.rb:22:in `block (3 levels) in <top (required)>'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:441:in `instance_exec'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:441:in `block in make_lambda'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:342:in `block in simple'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:497:in `block in around'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:505:in `call'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:343:in `block (2 levels) in simple'",
 "/usr/local/bundle/gems/i18n-0.9.5/lib/i18n.rb:268:in `with_locale'",
 "/usr/local/bundle/gems/activejob-4.2.10/lib/active_job/translation.rb:7:in `block (2 levels) in <module:Translation>'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:441:in `instance_exec'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:441:in `block in make_lambda'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:342:in `block in simple'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:497:in `block in around'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:505:in `call'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:343:in `block (2 levels) in simple'",
 "/usr/local/bundle/gems/activejob-4.2.10/lib/active_job/logging.rb:23:in `block (4 levels) in <module:Logging>'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/notifications.rb:164:in `block in instrument'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/notifications/instrumenter.rb:20:in `instrument'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/notifications.rb:164:in `instrument'",
 "/usr/local/bundle/gems/activejob-4.2.10/lib/active_job/logging.rb:22:in `block (3 levels) in <module:Logging>'",
 "/usr/local/bundle/gems/activejob-4.2.10/lib/active_job/logging.rb:45:in `tag_logger'",
 "/usr/local/bundle/gems/activejob-4.2.10/lib/active_job/logging.rb:19:in `block (2 levels) in <module:Logging>'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:441:in `instance_exec'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:441:in `block in make_lambda'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:342:in `block in simple'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:497:in `block in around'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:505:in `call'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:92:in `__run_callbacks__'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:778:in `_run_perform_callbacks'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:81:in `run_callbacks'",
 "/usr/local/bundle/gems/activejob-4.2.10/lib/active_job/execution.rb:31:in `perform_now'",
 "/usr/local/bundle/gems/activejob-4.2.10/lib/active_job/execution.rb:21:in `execute'",
 "/usr/local/bundle/gems/shoryuken-2.0.11/lib/shoryuken/extensions/active_job_adapter.rb:78:in `perform'",
 "/usr/local/bundle/gems/shoryuken-2.0.11/lib/shoryuken/processor.rb:22:in `block in process'",
 "/usr/local/bundle/gems/shoryuken-2.0.11/lib/shoryuken/middleware/chain.rb:94:in `block in invoke'",
 "/usr/local/bundle/gems/shoryuken-2.0.11/lib/shoryuken/middleware/server/active_record.rb:6:in `call'",
 "/usr/local/bundle/gems/shoryuken-2.0.11/lib/shoryuken/middleware/chain.rb:96:in `block in invoke'",
 "/usr/local/bundle/gems/shoryuken-2.0.11/lib/shoryuken/middleware/server/auto_extend_visibility.rb:12:in `call'",
 "/usr/local/bundle/gems/shoryuken-2.0.11/lib/shoryuken/middleware/chain.rb:96:in `block in invoke'",
 "/usr/local/bundle/gems/shoryuken-2.0.11/lib/shoryuken/middleware/server/auto_delete.rb:6:in `call'",
 "/usr/local/bundle/gems/shoryuken-2.0.11/lib/shoryuken/middleware/chain.rb:96:in `block in invoke'",
 "/usr/local/bundle/gems/shoryuken-2.0.11/lib/shoryuken/middleware/server/exponential_backoff_retry.rb:9:in `call'",
 "/usr/local/bundle/gems/shoryuken-2.0.11/lib/shoryuken/middleware/chain.rb:96:in `block in invoke'",
 "/usr/local/bundle/gems/shoryuken-2.0.11/lib/shoryuken/middleware/server/timing.rb:14:in `block in call'",
 "/usr/local/bundle/gems/shoryuken-2.0.11/lib/shoryuken/logging.rb:21:in `with_context'",
 "/usr/local/bundle/gems/shoryuken-2.0.11/lib/shoryuken/middleware/server/timing.rb:8:in `call'",
 "/usr/local/bundle/gems/shoryuken-2.0.11/lib/shoryuken/middleware/chain.rb:96:in `block in invoke'",
 "/usr/local/bundle/gems/shoryuken-2.0.11/lib/shoryuken/middleware/chain.rb:99:in `invoke'",
 "/usr/local/bundle/gems/shoryuken-2.0.11/lib/shoryuken/processor.rb:21:in `process'",
 "/usr/local/bundle/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'",
 "/usr/local/bundle/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'",
 "/usr/local/bundle/gems/celluloid-0.16.0/lib/celluloid/calls.rb:122:in `dispatch'",
 "/usr/local/bundle/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'",
 "/usr/local/bundle/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'",
 "/usr/local/bundle/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'",
 "/usr/local/bundle/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'",
 "/usr/local/bundle/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'"]



JOB ID: f74d432d-8358-4aef-8a09-355c30cd54f9

019-05-10T18:17:59Z 140 TID-gs5avtcek ActiveJob/EpisodeImportJob/production_cms_podcast_import/f74d432d-8358-4aef-8a09-355c30cd54f9 ERROR: Could not log "sql.active_record" event. NoMethodError: undefined method `end=' for nil:NilClass ["/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/subscriber.rb:96:in `finish'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/log_subscriber.rb:83:in `finish'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/notifications/fanout.rb:102:in `finish'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/notifications/fanout.rb:46:in `block in finish'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/notifications/fanout.rb:46:in `each'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/notifications/fanout.rb:46:in `finish'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/notifications/instrumenter.rb:36:in `finish'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/notifications/instrumenter.rb:25:in `instrument'",
 "/usr/local/bundle/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'",
 "/usr/local/bundle/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:317:in `execute'",
 "/usr/local/bundle/gems/activerecord-4.2.10/lib/active_record/connection_adapters/mysql2_adapter.rb:217:in `execute'",
 "/usr/local/bundle/gems/activerecord-4.2.10/lib/active_record/connection_adapters/mysql2_adapter.rb:238:in `exec_delete'",
 "/usr/local/bundle/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/database_statements.rb:114:in `update'",
 "/usr/local/bundle/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/query_cache.rb:14:in `update'",
 "/usr/local/bundle/gems/activerecord-4.2.10/lib/active_record/relation.rb:88:in `_update_record'",
 "/usr/local/bundle/gems/activerecord-4.2.10/lib/active_record/persistence.rb:515:in `_update_record'",
 "/usr/local/bundle/gems/activerecord-4.2.10/lib/active_record/locking/optimistic.rb:79:in `_update_record'",
 "/usr/local/bundle/gems/activerecord-4.2.10/lib/active_record/attribute_methods/dirty.rb:129:in `_update_record'",
 "/usr/local/bundle/gems/activerecord-4.2.10/lib/active_record/callbacks.rb:310:in `block in _update_record'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:88:in `__run_callbacks__'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:778:in `_run_update_callbacks'",
 "/usr/local/bundle/gems/activerecord-4.2.10/lib/active_record/callbacks.rb:310:in `_update_record'",
 "/usr/local/bundle/gems/activerecord-4.2.10/lib/active_record/timestamp.rb:70:in `_update_record'",
 "/usr/local/bundle/gems/activerecord-4.2.10/lib/active_record/persistence.rb:504:in `create_or_update'",
 "/usr/local/bundle/gems/activerecord-4.2.10/lib/active_record/callbacks.rb:302:in `block in create_or_update'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:117:in `call'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:505:in `call'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:92:in `__run_callbacks__'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:778:in `_run_save_callbacks'",
 "/usr/local/bundle/gems/activerecord-4.2.10/lib/active_record/callbacks.rb:302:in `create_or_update'",
 "/usr/local/bundle/gems/activerecord-4.2.10/lib/active_record/persistence.rb:142:in `save!'",
 "/usr/local/bundle/gems/activerecord-4.2.10/lib/active_record/validations.rb:43:in `save!'",
 "/usr/local/bundle/gems/activerecord-4.2.10/lib/active_record/attribute_methods/dirty.rb:29:in `save!'",
 "/usr/local/bundle/gems/activerecord-4.2.10/lib/active_record/transactions.rb:291:in `block in save!'",
 "/usr/local/bundle/gems/activerecord-4.2.10/lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'",
 "/usr/local/bundle/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/database_statements.rb:211:in `transaction'",
 "/usr/local/bundle/gems/activerecord-4.2.10/lib/active_record/transactions.rb:220:in `transaction'",
 "/usr/local/bundle/gems/activerecord-4.2.10/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'",
 "/usr/local/bundle/gems/activerecord-4.2.10/lib/active_record/transactions.rb:291:in `save!'",
 "/usr/local/bundle/gems/newrelic_rpm-5.2.0.345/lib/new_relic/agent/instrumentation/active_record_helper.rb:33:in `block in save!'",
 "/usr/local/bundle/gems/newrelic_rpm-5.2.0.345/lib/new_relic/agent/transaction.rb:918:in `with_database_metric_name'",
 "/usr/local/bundle/gems/newrelic_rpm-5.2.0.345/lib/new_relic/agent.rb:645:in `with_database_metric_name'",
 "/usr/local/bundle/gems/newrelic_rpm-5.2.0.345/lib/new_relic/agent/instrumentation/active_record_helper.rb:32:in `save!'",
 "/usr/local/bundle/gems/activerecord-4.2.10/lib/active_record/persistence.rb:265:in `block in update!'",
 "/usr/local/bundle/gems/activerecord-4.2.10/lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'",
 "/usr/local/bundle/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'",
 "/usr/local/bundle/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'",
 "/usr/local/bundle/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'",
 "/usr/local/bundle/gems/activerecord-4.2.10/lib/active_record/transactions.rb:220:in `transaction'",
 "/usr/local/bundle/gems/activerecord-4.2.10/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'",
 "/usr/local/bundle/gems/activerecord-4.2.10/lib/active_record/persistence.rb:263:in `update!'",
 "/app/app/models/story_distributions/episode_distribution.rb:60:in `create_or_update_episode'",
 "/app/app/models/episode_import.rb:250:in `create_or_update_episode!'",
 "/app/app/models/episode_import.rb:66:in `import'",
 "/app/app/jobs/episode_import_job.rb:7:in `perform'",
 "/usr/local/bundle/gems/activejob-4.2.10/lib/active_job/execution.rb:32:in `block in perform_now'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:117:in `call'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:505:in `call'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:343:in `block (2 levels) in simple'",
 "/app/app/jobs/application_job.rb:12:in `block (2 levels) in <class:ApplicationJob>'",
 "/usr/local/bundle/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'",
 "/app/app/jobs/application_job.rb:11:in `block in <class:ApplicationJob>'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:441:in `instance_exec'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:441:in `block in make_lambda'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:342:in `block in simple'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:497:in `block in around'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:505:in `call'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:343:in `block (2 levels) in simple'",
 "/usr/local/bundle/gems/newrelic_rpm-5.2.0.345/lib/new_relic/agent/transaction.rb:110:in `wrap'",
 "/usr/local/bundle/gems/newrelic_rpm-5.2.0.345/lib/new_relic/agent/instrumentation/active_job.rb:63:in `run_in_transaction'",
 "/usr/local/bundle/gems/newrelic_rpm-5.2.0.345/lib/new_relic/agent/instrumentation/active_job.rb:52:in `perform'",
 "/usr/local/bundle/gems/newrelic_rpm-5.2.0.345/lib/new_relic/agent/instrumentation/active_job.rb:22:in `block (3 levels) in <top (required)>'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:441:in `instance_exec'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:441:in `block in make_lambda'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:342:in `block in simple'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:497:in `block in around'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:505:in `call'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:343:in `block (2 levels) in simple'",
 "/usr/local/bundle/gems/i18n-0.9.5/lib/i18n.rb:268:in `with_locale'",
 "/usr/local/bundle/gems/activejob-4.2.10/lib/active_job/translation.rb:7:in `block (2 levels) in <module:Translation>'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:441:in `instance_exec'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:441:in `block in make_lambda'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:342:in `block in simple'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:497:in `block in around'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:505:in `call'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:343:in `block (2 levels) in simple'",
 "/usr/local/bundle/gems/activejob-4.2.10/lib/active_job/logging.rb:23:in `block (4 levels) in <module:Logging>'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/notifications.rb:164:in `block in instrument'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/notifications/instrumenter.rb:20:in `instrument'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/notifications.rb:164:in `instrument'",
 "/usr/local/bundle/gems/activejob-4.2.10/lib/active_job/logging.rb:22:in `block (3 levels) in <module:Logging>'",
 "/usr/local/bundle/gems/activejob-4.2.10/lib/active_job/logging.rb:45:in `tag_logger'",
 "/usr/local/bundle/gems/activejob-4.2.10/lib/active_job/logging.rb:19:in `block (2 levels) in <module:Logging>'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:441:in `instance_exec'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:441:in `block in make_lambda'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:342:in `block in simple'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:497:in `block in around'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:505:in `call'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:92:in `__run_callbacks__'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:778:in `_run_perform_callbacks'",
 "/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:81:in `run_callbacks'",
 "/usr/local/bundle/gems/activejob-4.2.10/lib/active_job/execution.rb:31:in `perform_now'",
 "/usr/local/bundle/gems/activejob-4.2.10/lib/active_job/execution.rb:21:in `execute'",
 "/usr/local/bundle/gems/shoryuken-2.0.11/lib/shoryuken/extensions/active_job_adapter.rb:78:in `perform'",
 "/usr/local/bundle/gems/shoryuken-2.0.11/lib/shoryuken/processor.rb:22:in `block in process'",
 "/usr/local/bundle/gems/shoryuken-2.0.11/lib/shoryuken/middleware/chain.rb:94:in `block in invoke'",
 "/usr/local/bundle/gems/shoryuken-2.0.11/lib/shoryuken/middleware/server/active_record.rb:6:in `call'",
 "/usr/local/bundle/gems/shoryuken-2.0.11/lib/shoryuken/middleware/chain.rb:96:in `block in invoke'",
 "/usr/local/bundle/gems/shoryuken-2.0.11/lib/shoryuken/middleware/server/auto_extend_visibility.rb:12:in `call'",
 "/usr/local/bundle/gems/shoryuken-2.0.11/lib/shoryuken/middleware/chain.rb:96:in `block in invoke'",
 "/usr/local/bundle/gems/shoryuken-2.0.11/lib/shoryuken/middleware/server/auto_delete.rb:6:in `call'",
 "/usr/local/bundle/gems/shoryuken-2.0.11/lib/shoryuken/middleware/chain.rb:96:in `block in invoke'",
 "/usr/local/bundle/gems/shoryuken-2.0.11/lib/shoryuken/middleware/server/exponential_backoff_retry.rb:9:in `call'",
 "/usr/local/bundle/gems/shoryuken-2.0.11/lib/shoryuken/middleware/chain.rb:96:in `block in invoke'",
 "/usr/local/bundle/gems/shoryuken-2.0.11/lib/shoryuken/middleware/server/timing.rb:14:in `block in call'",
 "/usr/local/bundle/gems/shoryuken-2.0.11/lib/shoryuken/logging.rb:21:in `with_context'",
 "/usr/local/bundle/gems/shoryuken-2.0.11/lib/shoryuken/middleware/server/timing.rb:8:in `call'",
 "/usr/local/bundle/gems/shoryuken-2.0.11/lib/shoryuken/middleware/chain.rb:96:in `block in invoke'",
 "/usr/local/bundle/gems/shoryuken-2.0.11/lib/shoryuken/middleware/chain.rb:99:in `invoke'",
 "/usr/local/bundle/gems/shoryuken-2.0.11/lib/shoryuken/processor.rb:21:in `process'",
 "/usr/local/bundle/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'",
 "/usr/local/bundle/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'",
 "/usr/local/bundle/gems/celluloid-0.16.0/lib/celluloid/calls.rb:122:in `dispatch'",
 "/usr/local/bundle/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'",
 "/usr/local/bundle/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'",
 "/usr/local/bundle/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'",
 "/usr/local/bundle/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'",
 "/usr/local/bundle/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'"]
```
